EXTRAKEY_ENABLE = yes
NKRO_ENABLE     = yes
OLED_ENABLE 	= yes
RGBLIGHT_ENABLE    = no
RGB_MATRIX_ENABLE  = yes

# Space saving
LTO_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MUSIC_ENABLE = no
